[package]
name = "realm"
version = "0.1.0"
authors = ["Erik Tate <hello@eriktate.me>"]
edition = "2018"

[dependencies]
gl = "0.14.0"
glfw = "0.37.0"
image = "0.23.4"
rand = "0.7.3"
rand_chacha = "0.2.2"
noise = "0.6.0"
